apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: upload-service-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: upload-service:latest
          imagePullPolicy: Never
          command: [ "celery" ]
          args:
            - "-A"
            - "app.celery_app"
            - "worker"
            - "--loglevel=info"
            - "--queues=default,document_processing"
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:postgres@postgres-service:5432/postgres"
            - name: CELERY_BROKER_URL
              value: "redis://redis-service.upload-service-ns.svc.cluster.local:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-service.upload-service-ns.svc.cluster.local:6379/0"
            - name: PYTHONPATH
              value: "/app"
          envFrom:
            - secretRef:
                name: upload-secrets
          resources:
            requests:
              memory: "512Mi"  # Worker может требовать больше памяти
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"