apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: upload-service-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: upload-service:latest
          imagePullPolicy: Never
          command: [ "celery" ]
          args:
            - "-A"
            - "app.celery_app"
            - "worker"
            - "--loglevel=$(CELERY_LOG_LEVEL)"
            - "--queues=$(CELERY_QUEUES)"
          env:
            # Из ConfigMap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: postgres-user
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: postgres-port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: postgres-db
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: redis-port
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: redis-db
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: pythonpath
            - name: CELERY_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: celery-log-level
            - name: CELERY_QUEUES
              valueFrom:
                configMapKeyRef:
                  name: upload-config
                  key: celery-queues

            # Из Secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: postgres-password

            # Собранные URL
            - name: DATABASE_URL
              value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            - name: CELERY_BROKER_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)/$(REDIS_DB)"
            - name: CELERY_RESULT_BACKEND
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)/$(REDIS_DB)"

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"