apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upload-ingress
  namespace: upload-service-ns
  annotations:
    # Будущие аннотации для LoadBalancer, SSL и т.д.
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: upload-web
            port:
              number: 8000